### ISSUE TITLE
Issue with Gutenberg 6.4

### ISSUE THREAD

**Issue by nick6352683** [AdvancedCustomFields/acf#218]
Hi Elliot,

They released Gutenberg 6.4 earlier today. Before this update  when making changes to some ACF fields and immediately clicking the update post button and then the view, we would get a message notifying that the post is not saved, BUT this was false, since it was ALWAYS saved. So the message was falsely triggered.

Now, however, things are much worse. It does not matter what block I edit, ACF or not, it does not what type of a fields I edit, text, etc... when trying to view the post/page after saving it, the warning shows it's ugly head, but again, they are always false, the changes are always saved. The issue goes away by Deactivating ACF Pro...

Just a heads up...

**Comment by elliotcondon** [comment]
Hi @nick6352683 

Thanks for the bug report. This doesn't sound great. Can you please take a short screen recording of the issue to help me better understand how to replicate it?

**Comment by nick6352683** [comment]
This is how to replicate it. Install the latest versions of WP, Gutenberg (v6.4.0) and ACF Pro. Any editing you do to a page/post you will get FALSE the notification (ACF Blocks or not). My test machine is Windows 7 Pro, using XAMP with php 7.2. Here is the short video.

https://www.youtube.com/watch?v=crNVd3Kt8Z0&feature=youtu.be

**Comment by elliotcondon** [comment]
@nick6352683 Thanks mate. I'll perform some testing shortly and will be in touch.

**Comment by nick6352683** [comment]
@elliotcondon - Hi Elliot,

Unfortunately the issue still exists even with the new ACF Pro update (Gutenberg 6.4 & ACF Pro 5.8.4).

**Comment by manuel-84** [comment]
For me when ACF is active I can save the post the first time, then due to error 500 the Update button stay freezed

> Error Details
> =============
> An error of type E_ERROR was caused in line 317 of the file wp-content/themes/mytheme/inc/acf/includes/forms/form-post.php. Error message: Uncaught Error: Call to undefined function acf_save_post_revision() in acf/includes/forms/form-post.php:317
> Stack trace:
> #0 wp-includes/class-wp-hook.php(288): ACF_Form_Post->save_post(2, Object(WP_Post))
> #1 wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
> #2 wp-includes/plugin.php(465): WP_Hook->do_action(Array)
> #3 wp-includes/post.php(3951): do_action('save_post', 2, Object(WP_Post), true)
> #4 wp-includes/post.php(4028): wp_insert_post(Array, false)
> #5 wp-admin/includes/post.php(405): wp_update_post(Array)
> #6 wp-admin/post.php(218): edit_post()
> #7 {main}

**Comment by elliotcondon** [comment]
@manuel-84 

This PHP error states that the `acf_save_post_revision()` function does not exist. This function is defined in the ACF file "includes/revisions.php" and is included in ACF's initialization.

Can you please check that this file exists and is readable?

**Comment by manuel-84** [comment]
@elliotcondon thanks you was right, for some reason ftp failed to upload this file
I tested all again and it's working

**Comment by taylordesignchris** [comment]
> @elliotcondon - Hi Elliot,
> 
> Unfortunately the issue still exists even with the new ACF Pro update (Gutenberg 6.4 & ACF Pro 5.8.4).

I'm getting this issue as well. It goes away if I deactivate the gutenberg plugin, or acf. It isn't happening for me if I use ACF and the stock Wordpress version of gutenberg.

**Comment by markhowellsmead** [comment]
@elliotcondon Possibly related (created as I have feedback that the same issue might be occurring without ACF): https://github.com/WordPress/gutenberg/issues/17395

**Comment by nick6352683** [comment]
@elliotcondon - Please note that Gutenberg 6.5 released earlier today does not solve the problem on hand...

**Comment by nick6352683** [comment]
Besides the issue mentioned above, there is now another issue... after updating to Gutenberg 6.5, and when using ACF Blocks on posts/pages, I randomly get a message "The backup of this post in your browser is different from the version below". Restoring the so called backup does not solve the issue, nor does the content changes. It seems that closing the browser (Chrome), solves the situation. I did not try things with Firefox.

Everything seems fine when the post/page does not contain ACF Blocks. I will do more testing and keep reporting back here with any more findings.

Things are definitely getting worse with every new Gut. update... also note that it was announced that this current Gut. version V6.5 will make it into core - WP v5.3, which will come sooner than we think...

**Comment by elliotcondon** [comment]
Hi @nick6352683 

Thanks for the update. I started testing with Gutenberg 6.5 yesterday and will be sure to checkout this issue too.

**Comment by nick6352683** [comment]
@elliotcondon :
Thanks Elliot,

A quick update, the new message "The backup of this post in your browser is different from the version below.", is also happening with Firefox - so it's not just Chrome based issue...

**Comment by nick6352683** [comment]
@elliotcondon ,

Hi Elliot,

Just starting to test WP 5.3 beta 1, and not surprisingly both wrongly warning messages are showing up. Again, both messages appear only on pages/posts that contain ACF Blocks. Is there a filter to mute them for good, even in cases that the messages are true? Right now, they are all false positives...

**Comment by elliotcondon** [comment]
Hi @nick6352683

Looks like the target release date for WordPress 5.3 is November 12:
https://make.wordpress.org/core/5-3/

I'll be testing thoroughly over the next month to ensure these issues are fixed in time.

**Comment by nick6352683** [comment]
Thanks Elliot,

I really admire how cool and confident you are...

**Comment by elliotcondon** [comment]
@nick6352683 

I've tracked down the "Unsaved Changes Prompt" issue, which is related to the "The backup of this post in your browser is different from the version below" issue, to a bug in core.

I've submitted a ticket here and will hope to see this fixed by the WordPress team: https://core.trac.wordpress.org/ticket/48132

**Comment by nick6352683** [comment]
Very impressive, let's see if these core guys will do anything for us...

As usual, thanks a million Elliot.

**Comment by nick6352683** [comment]
@elliotcondon , Hi Elliot,

I think we have a resolution on this, following the links from your bug report, I ended up here: https://github.com/WordPress/gutenberg/pull/17532 - and it seems like they already fixed this issue, and merged it to core already. I'm guessing, we will see the fix with the next Gutenberg or WP 5.3 beta 2 update. 

If you don't mind, I will keep this still open, until I can verify their fix is actually working - don't worry, as a theme and plugin developer, I keep tabs on these things very closely, maybe to a level of stalking!!!

Thanks for pushing them to resolve this, it was driving me crazy for a month now...

**Comment by nick6352683** [comment]
Just an update: They just released WP 5.3 beta 2, and the issue is still not fixed, even though according to the ticket dealing with this says that the patch has been merged (to Gutenberg). I wonder if before Nov. 12, the latest Gutenberg built will be included in the core, or we have to wait for Gutenberg 6.6 and install it on our WP installations just to get rid of this bug!

**Comment by nick6352683** [comment]
Ok, so this is weird... Using the Duplicator plugin I moved my test site to a newer laptop, still running Windows 7 Pro, and with WP 5.3 beta2, none of the messages are showing up... I have to conclude that something on that older was causing the false messages... I guess I can safely close this issue now, besides it was really a Gut. issue and not an ACF issues after all...

**Comment by elliotcondon** [comment]
Thanks @nick6352683 

Exciting! I'll do some testing today and let you know my findings.

**Comment by nick6352683** [comment]
Thanks once again Elliot, yes, at this point, having another eye on this (or two) would be a good idea...

**Comment by nick6352683** [comment]
Well, today I'm getting both messages on that newer laptop too! Again, running WP 5.3 beta 2, I even tried with the Gutenberg plugin 6.6 (released today). BTW, Gut. v6.6 is supposed to be in WP 5.3 beta2...

The issue is clearly not fixed... reopening the case...

**Comment by markhowellsmead** [comment]
Same here. 6.6 with 5.2 and 5.3 beta.

**Comment by nick6352683** [comment]
Ok, unless it's a coincidence, I found a way to avoid the messages all together. Note: This is not a fix, just avoidance...

1. Logging to your site.
2. Open a second tab (I only tested this with Chrome...).
3. Never close the original tab from step 1 !!!
4. Edit any page/post, and you will not see any of the messages.

However, if you create a new page, go on the frontend to view it, and when trying to edit that page, you will get the second message (the one that says the backup is not the same.

To avoid this annoyance, close your browser all together, and then redo steps 1 and 2 from above...

Crazy stuff, but so far, this is the only way to stop screaming at my laptops !!!

**Comment by nick6352683** [comment]
@markhowellsmead : I know Elliot will be doing some tests on this, can you also verify my findings above to avoid the messages?

Thanks...

**Comment by elliotcondon** [comment]
Hi all,

I've just updated to the latest nightly release (5.3-beta2-46373) and can confirm the issue appears to be fixed.

Making changes followed by navigating away from the page will trigger the unload prompt as expected. But once updated, there is no prompt to prevent navigating.

**Comment by nick6352683** [comment]
I agree... it fixed.

That said, I located the cause of my issue... As long as I'm using the plugin EditorsKit (Block Options), if a post/page contains ACF blocks, it will receive the messages... 

So, those who use ACF Blocks and the EditorsKit plugin will keep getting the unload prompt message...

As usual,
Thanks for everything Elliot.

**Comment by nick6352683** [comment]
Last Note: For those who are using the EditorsKit plugin, if you disable the Estimated Reading Time from the settings, avoids the issue...
