### ISSUE TITLE
Page preview doesn't work

### ISSUE THREAD

**Issue by Errabaany** [AdvancedCustomFields/acf#257]
I have a custom template ,
all of it's texts are editable with ACF , 
When I try to preview the page alll the editable text are made with ACF don't show ,
even if I change nothing ,

**Comment by elliotcondon** [comment]
Hi @Errabaany 

Thanks for the bug report. We are aware of the issue and will hope to have this fixed in an upcoming release :)

**Comment by MikePayne** [comment]
Has there been any progress on this issue, or is there a workaround to get it functioning as expected?

**Comment by elliotcondon** [comment]
Hi @MikePayne. No solution at this time. We're busy working towards our subscription/pricing changes, and will then regain focus on preview compatibility.

To confirm, is this issue with the classic or gutenberg editor?

**Comment by MikePayne** [comment]
@elliotcondon Thanks for the quick update. Do you have an ETA for when this might resurface on your priority list?

Originally, I had the issue with Gutenberg and it was resolved by installing the classic editor plugin. We've recently discovered that this solution only solved the issue on blog posts and pages, but not on my custom post types.

**Comment by Errabaany** [comment]
hope you fix the problem as soon as possible ,
my boss told me to work with different plugin , because the clients need to preview the changes before they save it or they can't work,
also i have to build all the previous websites that I developed with AFC from beginning with Elementor if the problem didn't solve asap

**Comment by elliotcondon** [comment]
Hi @MikePayne 

I'm sure the Classic Editor plugin provides compatibility with CPT. Please consult the documentation for more info.

**Comment by elliotcondon** [comment]
@Errabaany Thanks mate. I hope we solve it shortly too.

**Comment by kwells0722** [comment]
Fast forward 4 years, this is still an issue. As mentioned from users above we have a requirement for stakeholders to view site previews before publishing. We would like to get this amended.
