### ISSUE TITLE
ACF and PHP 7.4 a little notice

### ISSUE THREAD

**Issue by CreativeDive** [AdvancedCustomFields/acf#265]
Hey @elliotcondon ,

currently I get this little PHP notice, after updating to PHP 7.4:

**Trying to access array offset on value of type bool**
`acf/includes/api/api-template.php:499`

That's all :-)

**Comment by elliotcondon** [comment]
Thanks @CreativeDive 

Will look into this shortly.

**Comment by ulimc** [comment]
Hi @elliotcondon , I have this notice also on my server.
It presented itself while switching PHP to 7.4.2 like the user above.

**Comment by elliotcondon** [comment]
Hi all,

Thanks for your patience whilst we investigate the issue.

Good news. We have been able to find and fix the issue.
The problem occurs when calling `have_rows()` on a field that does not contain a value.

The fix is simple, please find the `have_rows()` function within the `/includes/api/api-template.php` file on line 357 and replace with the following:

```php
/**
 * have_rows
 *
 * Checks if a field (such as Repeater or Flexible Content) has any rows of data to loop over.
 * This function is intended to be used in conjunction with the_row() to step through available values.
 *
 * @date	2/09/13
 * @since	4.3.0
 *
 * @param	string $selector The field name or field key.
 * @param	mixed $post_id The post ID where the value is saved. Defaults to the current post.
 * @return	bool
 */
function have_rows( $selector, $post_id = false ) {
	
	// Validate and backup $post_id.
	$_post_id = $post_id;
	$post_id = acf_get_valid_post_id( $post_id );
	
	// Vars.
	$key = "selector={$selector}/post_id={$post_id}";
	$active_loop = acf_get_loop('active');
	$prev_loop = acf_get_loop('previous');
	$new_loop = false;
	$sub_field = false;
	
	// Check if no active loop.
	if( !$active_loop ) {
		$new_loop = 'parent';
	
	// Detect "change" compared to the active loop.
	} elseif( $key !== $active_loop['key'] ) {
		
		// Find sub field and check if a sub value exists.
		$sub_field_exists = false;
		$sub_field = acf_get_sub_field($selector, $active_loop['field']);
		if( $sub_field ) {
			$sub_field_exists = isset( $active_loop['value'][ $active_loop['i'] ][ $sub_field['key'] ] );
		}
		
		// Detect change in post_id.
		if( $post_id != $active_loop['post_id'] ) {
			
			// Case: Change in $post_id was due to this being a nested loop and not specifying the $post_id.
			// Action: Move down one level into a new loop.
			if( empty($_post_id) && $sub_field_exists ) {
				$new_loop = 'child';
			
			// Case: Change in $post_id was due to a nested loop ending.
			// Action: move up one level through the loops.
			} elseif( $prev_loop && $prev_loop['post_id'] == $post_id ) {
				acf_remove_loop('active');
				$active_loop = $prev_loop;
			
			// Case: Chang in $post_id is the most obvious, used in an WP_Query loop with multiple $post objects.
			// Action: leave this current loop alone and create a new parent loop.
			} else {
				$new_loop = 'parent';
			}
		
		// Detect change in selector.
		} elseif( $selector != $active_loop['selector'] ) {
			
			// Case: Change in $field_name was due to this being a nested loop.
			// Action: move down one level into a new loop.
			if( $sub_field_exists ) {
				$new_loop = 'child';
			
			// Case: Change in $field_name was due to a nested loop ending.
			// Action: move up one level through the loops.
			} elseif( $prev_loop && $prev_loop['selector'] == $selector && $prev_loop['post_id'] == $post_id ) {
				acf_remove_loop('active');
				$active_loop = $prev_loop;
			
			// Case: Change in $field_name is the most obvious, this is a new loop for a different field within the $post.
			// Action: leave this current loop alone and create a new parent loop.
			} else {
				$new_loop = 'parent';
			}
		}
	}
	
	// Add loop if required.
	if( $new_loop ) {
		$args = array(
			'key'		=> $key,
			'selector'	=> $selector,
			'post_id'	=> $post_id,
			'name'		=> null,
			'value'		=> null,
			'field'		=> null,
			'i'			=> -1,
		);
		
		// Case: Parent loop.
		if( $new_loop === 'parent' ) {
			$field = get_field_object( $selector, $post_id, false );
			if( $field ) {
				$args['field'] = $field;
				$args['value'] = $field['value'];
				$args['name'] = $field['name'];
				unset( $args['field']['value'] );
			}
			
		// Case: Child loop ($sub_field must exist).
		} else {
			$args['field'] = $sub_field;
			$args['value'] = $active_loop['value'][ $active_loop['i'] ][ $sub_field['key'] ];
			$args['name'] = "{$active_loop['name']}_{$active_loop['i']}_{$sub_field['name']}";
			$args['post_id'] = $active_loop['post_id'];
		}
		
		// Bail early if value is either empty or a non array.
		if( !$args['value'] || !is_array($args['value']) ) {
			return false;
		}
		
		// Allow for non repeatable data for Group and Clone fields.
		if( acf_get_field_type_prop($args['field']['type'], 'have_rows') === 'single' ) {
			$args['value'] = array( $args['value'] );
		}
		
		// Add loop.
		$active_loop = acf_add_loop($args);
	}
	
	// Return true if next row exists.
	if( $active_loop && isset($active_loop['value'][ $active_loop['i']+1 ]) ) {
		return true;
	}	
	
	// Return false if no next row.
	acf_remove_loop('active');
	return false;
}
```

Please test this out and let us know your results. The more feedback we can receive, the faster we will be able to release an update.

**Comment by CreativeDive** [comment]
Thanks @elliotcondon I've tested your fix and this PHP notice is no longer displayed 👍

**Comment by dsifford** [comment]
Is this going to be included in a release soon @elliotcondon?

**Comment by elliotcondon** [comment]
@dsifford Yes. ETA: 1 - 2 weeks.

**Comment by mostlybritts** [comment]
This fix worked for me.

**Comment by glagonikas** [comment]
@elliotcondon any updates on this?

**Comment by elliotcondon** [comment]
Hi @glagonikas - This issue was fixed back in February. Can you elaborate a little more about the issue you are having today?

**Comment by glagonikas** [comment]
Hi @elliotcondon 

Running PHP 7.4 and ACF Pro, while opening unrelated pages to ACF, such as order edit page, I get some notices `Trying to access array offset on value of type bool`

Stack trace:
```
wp-admin/includes/template.php:1079
add_meta_box()
  wp-admin/includes/template.php:1256
do_meta_boxes()
  wp-content/plugins/advanced-custom-fields-pro/includes/forms/form-post.php:182
ACF_Form_Post->edit_form_after_title()
  wp-includes/class-wp-hook.php:287
do_action('edit_form_after_title')
  wp-admin/edit-form-advanced.php:570
```

I thought this issue is related and unresolved (as it's still open).

I also sent a ticket through the website, but I don't see it on "my tickets" list

**Comment by elliotcondon** [comment]
@glagonikas Thanks for the information. I've just spent some time trying to replicate this error using PHP 7.4.1, but have not yet been able to replicate the problem.

The stack trace suggests there is a logic error occurring due to the saved "metabox order". I've tried all sorts of combinations of events to trigger the same problem, but can't seem to find the right scenario where the error is thrown.

How are your debugging skills? Are you able to debug the `wp-admin/includes/template.php:1079` line of code to better understand the logic going wrong?

**Comment by glagonikas** [comment]
Hi @elliotcondon Can you try with PHP 7.4.3+, although to be honest, I'm not 100% certain our problem is caused by ACF. I commented `do_meta_boxes( get_current_screen(), 'acf_after_title', $post );` in `wp-content/plugins/advanced-custom-fields-pro/includes/forms/form-post.php:182` and the issue persists without a reference to ACF, so it could be something specific to our site or caused by another plugin, so i will need to investigate further on our end and will report back if we still need assistance.

**Comment by glagonikas** [comment]
Think our issue (and possibly the one fixed in this issue) is caused by this https://core.trac.wordpress.org/ticket/50019 which should be resolved in WPv5.5

**Comment by danmurray2k** [comment]
This fixed my issue after upgrading to wordpress 5.9

**Comment by CreativeDive** [comment]
@lgladdy this issue could be closed :-)

**Comment by Janki-Patel-UI** [comment]
Hi, I have upgrade WordPress 6.2.2 and show "Warning: Trying to access array offset on value of type bool" in  plugins\custom-content-shortcode includes\core\content.php on line 1801 and custom content shortcode plugin has been closed as of March 28, 2023 and is not available for download. that is mention in official site. what should I do? please help me
