### ISSUE TITLE
HTML (svg) in select2 label getting escaped

### ISSUE THREAD

**Issue by JiveDig** [AdvancedCustomFields/acf#553]
I have a select2 field that's loading SVGs as options. This still works fine, however the selected svg is escaped so you visually see HTML.

<img width="313" alt="Markup 2021-09-10 at 16 36 42" src="https://user-images.githubusercontent.com/540990/132914799-c7339a61-0fa7-4a77-8b1e-0ff185c76562.png">

I'm loading the svg's via a sprite like this:

```
<svg class="mai-icon-svg"><use xlink:href="https://maitheme.local/success-business/wp-content/plugins/mai-icons/icons/sprites/light.svg#pencil-ruler"></use></svg><span class="mai-icon-name">pencil-ruler</span>
```

It looks like the escaping may be happening via JS so I'm not sure where dig to fix. Thanks y'all.

**Comment by JiveDig** [comment]
Same issue if I use an `<img>` or `<object>`.

**Comment by JiveDig** [comment]
Likely related to what I'm hitting: https://wordpress.org/support/topic/icons-not-appearing-in-back-end-after-acf-update/

**Comment by JiveDig** [comment]
Forgot to mention this didn't happen prior to 5.10 (I think) which is why I'm assuming it's the new escaping stuff.

**Comment by lgladdy** [comment]
Hey @JiveDig - did you add support for SVGs with [`wp_kses_allowed_html`](https://www.advancedcustomfields.com/resources/html-escaping/)?

**Comment by JiveDig** [comment]
Hi @lgladdy thanks for the reply. I did try that filter. I was seeing this issue with an `<img>` (with the svg as src) and `<object>` field as well.

Interesting update though. I deactivated Woo and Woo Subscriptions and it fixed it. Then I activated them both again and it's still working. That's a bit strange to me, but now it's working on my test site. I'm going to test this update of our plugin on some other sites and see what happens.

**Comment by lgladdy** [comment]
Hey @JiveDig. I think this is likely related to WooCommerce's 5.6 issue with loading the wrong version of Select2 - it should be fixed in 5.7.

**Comment by JiveDig** [comment]
Would toggling WooCommerce off/on change the version that's loaded? I didn't update anything today.

**Comment by lgladdy** [comment]
Nope - but it might change the order that WordPress loads select2 from us, and the malformed select2 from woocommerce.

**Comment by JiveDig** [comment]
Okay it does seem to be working everywhere else I'm testing. I'll close this and reopen or just update here if I hit it again with any other info. Thanks.

**Comment by JiveDig** [comment]
Not sure what changed, but this issue is back and toggling WooCommerce off/on doesn't fix it now. Gonna reopen ti see if anyone else is hitting this. FWIW we are loading ACF in our plugin so it may be running after Woo.

**Comment by JiveDig** [comment]
Confirming that commenting out:
```
wp_register_script( 'select2', WC()->plugin_url() . '/assets/js/select2/select2.full' . $suffix . '.js', array( 'jquery' ), '4.0.3' );
```
in woocommerce/includes/admin/wc-class-admin-assets.php `admin_scripts()` method does fix the issue. So it seems to be a conflict with load order for me. Argh.

**Comment by JiveDig** [comment]
Some interesting solutions to this conflict from Popup Maker https://stackoverflow.com/a/36815607

**Comment by lgladdy** [comment]
Hey @JiveDig 

Yeh, so this was the issue we have in the original 5.10 release. If you have WooCommerce installed, they don't support our new template for select2 with the broken version of select2 they shipped in WooCommerce 5.6.

We had to work around this by detecting in 5.10.1 if you've WooCommerce's broken Select2 is loaded - in that case we use a workaround so that things at least work properly - but WooCommerce's broken select2 is hard coded to strip out any HTML - we can't work around that at all.

This will all be fixed once WooCommerce 5.7 is released - we adapt to whatever valid version of select2 is loaded and make sure things work - but if their malformed Select2 (which is actually SelectWoo) is loaded, we pick the "least worst" option of compatibility - which means HTML doesn't work, but at least "[Object object]" isn't listed for everything.

**Comment by JiveDig** [comment]
A somewhat scary fix is adding 

```
if ( wp_script_is( 'select2', 'registered' ) ) {
     wp_deregister_script( 'select2' );
}
```

Just above 
```
wp_enqueue_script( 'select2', $script, array( 'jquery' ), $version );
wp_enqueue_style( 'select2', $style, '', $version );
```

in `input_admin_enqueue_scripts()` function for the select field.

**Comment by JiveDig** [comment]
For reference: https://github.com/woocommerce/selectWoo/issues/39

**Comment by lgladdy** [comment]
Info on the woocommerce issue is here: https://github.com/woocommerce/woocommerce/pull/30473

**Comment by JiveDig** [comment]
I'm not positive, but I just updated a local test/dev site to WC 7.0.0 and this issue seems to be fixed.
