### ISSUE TITLE
Function _load_textdomain_just_in_time was called incorrectly.

### ISSUE THREAD

**Issue by ve3** [AdvancedCustomFields/acf#949]
**Describe the bug**
This plugin cause error **Notice** Function _load_textdomain_just_in_time was called incorrectly.

**To Reproduce**
1. Install WordPress 6.8 beta with showing all errors.
2. Install and activate this plugin
3. Maybe create any simple custom field. Any.. (as easy as possible because it is nothing related to the custom fields, it's about your code).
4. Go to home page and error occur.

**Expected behavior**
Web page display without any errors.

**Screenshots or Video**
It's just error message.

**Code**
It's nothing related to the custom field. You can setup **ANY** kind of custom field as easy as possible. The problem is about your code calling translation function(s) incorrectly.

**Version Information:**
 - WordPress Version 6.8beta (6.8-beta3-60046)
 - PHP Version 8.3
 - ACF Version Free 6.3.12
 - Browser [e.g. chrome 103, safari 17]

Full error message:

> Notice: Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>acf</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href="https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.) in wp-includes\functions.php on line 6121
> 
> 5. require_once( 'wp-settings.php )
> 6. include_once( 'wp-content\plugins\advanced-custom-fields\acf.php )
> 7. acf( ) ...\acf.php:843
> 8. ACF->initialize( ) ...\acf.php:837
> 9. __( $text = 'Advanced Custom Fields', $domain = 'acf' ) ...\acf.php:93
> 10. translate( $text = 'Advanced Custom Fields', $domain = 'acf' ) ...\l10n.php:307
> 11. get_translations_for_domain( $domain = 'acf' ) ...\l10n.php:195
> 12. _load_textdomain_just_in_time( $domain = 'acf' ) ...\l10n.php:1409
> 13. _doing_it_wrong( $function_name = '_load_textdomain_just_in_time', $message = 'Translation loading for the <code>acf</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later.', $version = '6.7.0' ) ...\l10n.php:1371
> 14. wp_trigger_error( $function_name = '', $message = 'Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>acf</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href="https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.)', $error_level = ??? ) ...\functions.php:6061
> 15. [trigger_error](http://www.php.net/function.trigger-error)( $message = 'Function _load_textdomain_just_in_time was called <strong>incorrectly</strong>. Translation loading for the <code>acf</code> domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the <code>init</code> action or later. Please see <a href="https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 6.7.0.)', $error_level = 1024 ) ...\functions.php:6121

**Comment by lgladdy** [comment]
Hey there,

WordPress 6.8 introduces this notice when a plugin loads its translations too early.

ACF doesn't do this by default, but if you call an ACF function before ACF has initialised (which would be late enough to prevent the notice), such as `get_field`, ACF is forced to initialise early in order to give you the data you've requested.

So, this error means somewhere the code you've got calling ACF functions is firing before WordPress has run init. This is usually in functions.php in our experience, but it could be anywhere depending on how you develop with ACF.

If you wrap any calls to get_field in an `acf/init` action, you can be sure you don't trigger ACF to initialise too early.

**Comment by ve3** [comment]
No, it is not from `get_field`. This problem is not from my. The error details already told. 

And if you look into your code [here](https://github.com/AdvancedCustomFields/acf/commit/29d13eb7e043d1a9fa9c3ee01a65789121c8c8a2#diff-eed99b172bfef9f00638c9484dd5181b00a9d9469a2938532a99a0cbfd55c195L94) it was fixed on commit 29d13eb

You used to called `__()` too early by yourself !not! me. And you already fixed it by remove `__( 'Advanced Custom Fields', 'acf' ),`  and replace with just `'Advanced Custom Fields',`

**Comment by lgladdy** [comment]
Hey @ve3 

Apologies, we did fix ACF's side of this issue in 6.4.0, but since WordPress 6.8's release yesterday we've had numerous reports of this still happening as a result of user code making us initialise too early.

I included those details about function calls in the response to give users searching for this issue the resolution they'll need to fix it.

Thanks for the report,
Liam
